### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by abemedia** [PejmanNik/lazvard-message#4]
Would be great if this was wrapped into a docker image for easy testing in multiple languages.

**Comment by viachmev** [comment]
+1

**Comment by alexbezugliy** [comment]
Great idea - who can contribute this and what effort is required?

**Comment by PejmanNik** [comment]
The main issue is (was) handling certificates and SSL, but now most of the service bus client supports non-secure (HTTP) endpoint with the last release and it should be pretty straightforward now, but it also means MS is finalizing the official version of the service bus simulator and makes me wondering if it worth to spend time on this project 🤔😕

**Comment by zelda1998** [comment]
Im trying to create a docker container with this Dockerfile

```
FROM mcr.microsoft.com/dotnet/sdk:8.0 as build

WORKDIR /source
COPY . .

WORKDIR /source/src/Lazvard.Message.Cli

RUN dotnet restore
RUN dotnet publish --no-restore -o /app
RUN dotnet dev-certs https

RUN mv ~/.dotnet/corefx/cryptography/x509stores/my/*.pfx /app/cert.pfx

FROM mcr.microsoft.com/dotnet/runtime:8.0
WORKDIR /app

RUN apt-get update -y && apt-get install vim -y

COPY --from=build /app .

EXPOSE 5671
```

When i enter in container and start the CLI Manually, this error appears 

`Can't load the certificate. please check the certificate or use the built-in certificate manager
In order to troubleshoot the built-in certificate manager please use dotnet dev-certs documentation
Error: ValidCertificatePresent`

config.toml
![image](https://github.com/PejmanNik/lazvard-message/assets/73412507/d84c90f1-c911-4086-8caf-af0fb4412037)

**Comment by PejmanNik** [comment]
Hi, with the latest version 0.3.0, and the latest Azure SDK, you no longer need HTTPS and certificates for the local emulator. As long as you can map the container to localhost, containerization shouldn't have any challenges.

**Comment by raphaelm22** [comment]
I created a PR https://github.com/PejmanNik/lazvard-message/pull/9 to help in this insue

**Comment by PejmanNik** [comment]
Dockerfile (Containerfile) is in the repo now and I also published it in the docker hub `pejmann/lazvard-message`

Please check the readme in the repo for more info
